# Generated by Django 5.1.6 on 2026-04-22 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=32, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('language_preference', models.CharField(choices=[('kk', 'Kazakh'), ('ru', 'Russian'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('status', models.CharField(choices=[('new', 'New'), ('engaged', 'Engaged'), ('warm', 'Warm'), ('payment_intent', 'Payment intent'), ('receipt_received', 'Receipt received'), ('customer', 'Customer'), ('handed_off', 'Handed off'), ('lost', 'Lost')], default='new', max_length=32)),
                ('source', models.CharField(default='whatsapp', max_length=64)),
                ('handoff_needed', models.BooleanField(default=False)),
                ('existing_user_linked', models.BooleanField(default=False)),
                ('paid_access_granted', models.BooleanField(default=False)),
                ('last_user_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_bot_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_intent', models.CharField(blank=True, max_length=64, null=True)),
                ('message_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppAgentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='whatsapp_agent.whatsapplead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_message_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound'), ('outbound', 'Outbound'), ('system', 'System')], max_length=16)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('document', 'Document'), ('audio', 'Audio'), ('interactive', 'Interactive'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('text_content', models.TextField(blank=True)),
                ('media_id', models.CharField(blank=True, max_length=255)),
                ('media_mime_type', models.CharField(blank=True, max_length=255)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('delivered', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('failed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp_agent.whatsapplead')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('file', models.FileField(blank=True, null=True, upload_to='whatsapp_receipts/%Y/%m/%d/')),
                ('extracted_text', models.TextField(blank=True)),
                ('amount_detected', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('receiver_phone_detected', models.CharField(blank=True, max_length=32)),
                ('receiver_name_detected', models.CharField(blank=True, max_length=255)),
                ('timestamp_detected', models.DateTimeField(blank=True, null=True)),
                ('validation_confidence', models.FloatField(default=0)),
                ('is_validated', models.BooleanField(default=False)),
                ('validation_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='whatsapp_agent.whatsapplead')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='whatsapp_agent.whatsappmessage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
