# Generated by Django 5.1.6 on 2025-02-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Сабақ атауы')),
                ('content', models.TextField(verbose_name='Сабақ мәтіні')),
                ('vocabulary', models.TextField(verbose_name='Сөздік')),
                ('grammar', models.TextField(verbose_name='Грамматика')),
                ('dialogue', models.TextField(verbose_name='Диалог')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Құру уақыты')),
            ],
        ),
    ]
