# Generated by Django 5.1.6 on 2025-03-10 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, verbose_name='Қолданушы ID')),
                ('score', models.IntegerField(default=0, verbose_name='Ұпай саны')),
                ('attempts', models.IntegerField(default=0, verbose_name='Қателер саны')),
                ('completed', models.BooleanField(default=False, verbose_name='Өтіп болды ма?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Өту уақыты')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='lessons.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_word', models.CharField(max_length=100, verbose_name='Ағылшынша сөз')),
                ('kazakh_translation', models.CharField(max_length=255, verbose_name='Қазақша аударма')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='lessons.lesson')),
            ],
        ),
    ]
