# Generated by Django 5.1.6 on 2025-03-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_quizattempt_quizquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='is_passed',
            field=models.BooleanField(default=False, verbose_name='Тест сәтті өтті ме?'),
        ),
    ]
