# Generated by Django 5.1.6 on 2025-03-16 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_quizattempt_is_passed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Explanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('content', 'Сабақ мазмұны'), ('vocabulary', 'Сөздік'), ('grammar', 'Грамматика'), ('dialogue', 'Диалог')], max_length=20)),
                ('text', models.TextField(verbose_name='Түсіндірме мәтіні')),
                ('audio_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Аудио сілтемесі')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Құру уақыты')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explanations', to='lessons.lesson')),
            ],
            options={
                'unique_together': {('lesson', 'section')},
            },
        ),
    ]
