# Generated by Django 5.1.6 on 2025-07-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0006_lead"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_paid",
            field=models.BooleanField(
                default=False, verbose_name="Ақылы қолданушы ма?"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Телефон нөмірі"
            ),
        ),
    ]
