# Generated by Django 5.1.6 on 2025-08-27 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0007_userprofile_is_paid_userprofile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="current_lesson",
            field=models.IntegerField(default=1, verbose_name="Қазіргі сабақ"),
        ),
    ]
