# Generated by Django 5.1.6 on 2025-09-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_userprofile_current_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_voice_access',
            field=models.BooleanField(default=False, verbose_name='Дауыс сабағына қол жеткізу'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='voice_access_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дауыс сабағы мерзімі'),
        ),
    ]
