# Generated by Django 5.1.6 on 2025-11-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0009_userprofile_has_voice_access_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="has_translator_access",
            field=models.BooleanField(
                default=False, verbose_name="Аудармашы көмекшісіне қол жеткізу"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="translator_access_until",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Аудармашы мерзімі"
            ),
        ),
    ]
