# Generated by Django 5.1.6 on 2026-01-12 08:15

import django.db.models.deletion
import lessons.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0010_userprofile_has_translator_access_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('student', 'Оқушы'), ('teacher', 'Мұғалім')], default='student', max_length=20, verbose_name='Рөлі'),
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Сынып атауы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Құрылды')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Жаңартылды')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('teacher', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ClassStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Оқушы аты-жөні')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Ескертпе')),
                ('face_embedding', models.JSONField(blank=True, null=True, verbose_name='Face embedding')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Құрылды')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='lessons.classgroup')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_students', to=settings.AUTH_USER_MODEL, verbose_name='Тіркелген қолданушы')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=lessons.models.student_face_upload_path, verbose_name='Face photo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Құрылды')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='lessons.classstudent')),
            ],
        ),
    ]
