# Generated by Django 5.1.6 on 2026-01-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0011_userprofile_role_classgroup_classstudent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classstudent',
            name='voice_embeddings',
            field=models.JSONField(blank=True, default=list, verbose_name='Voice embeddings'),
        ),
    ]
