# Generated by Django 5.1.6 on 2026-01-18 11:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0012_classstudent_voice_embeddings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='classgroup',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='classgroup',
            name='school_name',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='Мектеп атауы'),
        ),
        migrations.AlterUniqueTogether(
            name='classgroup',
            unique_together={('teacher', 'school_name', 'name')},
        ),
    ]
