# Generated by Codex on 2026-06-30

from django.db import migrations
from django.db.models import Count


def dedupe_quiz_attempts(apps, schema_editor):
    QuizAttempt = apps.get_model("lessons", "QuizAttempt")

    duplicates = (
        QuizAttempt.objects.values("user_id", "lesson_id")
        .annotate(row_count=Count("id"))
        .filter(row_count__gt=1)
    )

    for duplicate in duplicates.iterator():
        attempts = list(
            QuizAttempt.objects.filter(
                user_id=duplicate["user_id"],
                lesson_id=duplicate["lesson_id"],
            )
        )
        attempts.sort(
            key=lambda attempt: (
                bool(attempt.is_passed),
                bool(attempt.completed),
                attempt.score or 0,
                attempt.id or 0,
            ),
            reverse=True,
        )
        keep = attempts[0]
        QuizAttempt.objects.filter(
            user_id=duplicate["user_id"],
            lesson_id=duplicate["lesson_id"],
        ).exclude(id=keep.id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0014_quizanswer"),
    ]

    operations = [
        migrations.RunPython(dedupe_quiz_attempts, migrations.RunPython.noop),
    ]
