# Generated by Codex on 2026-06-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lessons", "0015_dedupe_quizattempt"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="quizattempt",
            constraint=models.UniqueConstraint(
                fields=("user_id", "lesson"),
                name="unique_quiz_attempt_per_user_lesson",
            ),
        ),
    ]
